name: tfa
description: "Collection of classes to create manageable Flutter architecture"
version: 0.0.1
homepage: https://github.com/bysensa/the-flutter-architecture

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.19.5"

dependencies:
  flutter:
    sdk: flutter
  mobx: ^2.3.3+2
  nested: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
